import { NextRequest, NextResponse } from "next/server";
import { createSessionClient } from "@/lib/supabase/server-session";
import { requireTeacherForClass, teacherService } from "@/lib/teacher/server";
import { createZoomMeetingSdkSignature } from "@/lib/zoom/sdk-jwt";
import { ensureZoomWebinar, getZoomZak, loadZoomClassMetadata } from "@/lib/zoom/api";
import { getZoomConfig, zoomConfigStatus } from "@/lib/zoom/config";
export const dynamic="force-dynamic";export const runtime="nodejs";
export async function POST(request:NextRequest){try{const body=await request.json();const classId=String(body?.classId||"").trim();const mode=String(body?.mode||"student").toLowerCase();if(!classId||!["teacher","student"].includes(mode))return NextResponse.json({ok:false,error:"Valid classId and mode are required."},{status:400});const status=zoomConfigStatus();if(!status.configured)return NextResponse.json({ok:false,error:`Live Now webinar provider is not configured: ${status.missing.join(", ")}`},{status:503});const service=teacherService();const {data:liveClass,error:classError}=await service.from("live_classes").select("*").eq("id",classId).single();if(classError)throw classError;
if(mode==="teacher"){const staff=await requireTeacherForClass(classId);const webinar=await ensureZoomWebinar(service,liveClass);const c=getZoomConfig();const signature=createZoomMeetingSdkSignature({meetingNumber:webinar.webinarId,role:1});const zak=await getZoomZak(c.hostEmail);return NextResponse.json({ok:true,provider:"zoom",sdkKey:c.sdkClientId,signature,meetingNumber:webinar.webinarId,password:webinar.password,userName:staff.fullName,userEmail:c.hostEmail,zak,role:1,joinUrl:webinar.joinUrl});}
const session=await createSessionClient();const {data:{user}}=await session.auth.getUser();if(!user)return NextResponse.json({ok:false,error:"UNAUTHENTICATED"},{status:401});const [{data:assignment},{data:profile}]=await Promise.all([service.from("live_class_assignments").select("id").eq("live_class_id",classId).eq("student_id",user.id).eq("status","active").maybeSingle(),service.from("profiles").select("full_name,student_code,email").eq("id",user.id).maybeSingle()]);if(!assignment)return NextResponse.json({ok:false,error:"ACCESS_DENIED"},{status:403});const webinar=await loadZoomClassMetadata(service,classId);if(!webinar)return NextResponse.json({ok:false,error:"Live Now has not been opened by the teacher yet. Please try again shortly."},{status:409});const c=getZoomConfig();const signature=createZoomMeetingSdkSignature({meetingNumber:webinar.webinarId,role:0});return NextResponse.json({ok:true,provider:"zoom",sdkKey:c.sdkClientId,signature,meetingNumber:webinar.webinarId,password:webinar.password,userName:profile?.full_name||profile?.student_code||profile?.email||"Student",userEmail:profile?.email||user.email||"",zak:"",role:0,joinUrl:webinar.joinUrl});}catch(e:any){return NextResponse.json({ok:false,error:e?.message||"Unable to authorize Live Now webinar."},{status:Number(e?.status||500)});}}
