"use client";

import * as React from "react";
import Link from "next/link";
import { CalendarDays, Clock3, FileText, PlayCircle, Radio, Users, ArrowLeft, Lock } from "lucide-react";

export default function LiveClassesPage() {
  const [data,setData]=React.useState<any>(null);const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState("");
  React.useEffect(()=>{fetch("/api/live-class/student",{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw Object.assign(new Error(j.error||"Unable to load classes"),{status:r.status});return j}).then(setData).catch((e:any)=>setError(e.message||"Unable to load classes")).finally(()=>setLoading(false))},[]);
  return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-6xl px-4 py-6 sm:px-6"><Link href="/" className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Back to Ibemhal IAS</Link><section className="rounded-[2rem] bg-[#14256f] p-6 text-white shadow-xl sm:p-8"><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-black"><Radio className="h-4 w-4 text-red-400"/>Live Classes</div><h1 className="mt-4 text-3xl font-black sm:text-4xl">Your classroom, wherever you are.</h1><p className="mt-2 max-w-2xl text-sm text-white/70">Only classes assigned to your Student ID and purchased packages appear here.</p>{data?.profile&&<div className="mt-5 inline-flex rounded-xl bg-white/10 px-4 py-2 text-xs font-bold">Student ID: {data.profile.student_code} · {data.profile.full_name}</div>}</section>
  {loading&&<div className="mt-6 rounded-2xl bg-white p-8 text-center text-sm text-slate-500">Loading your access…</div>}
  {!loading&&error&&<div className="mt-6 rounded-3xl border border-amber-200 bg-amber-50 p-6 text-center"><Lock className="mx-auto h-8 w-8 text-amber-600"/><h2 className="mt-3 font-black">Student login required</h2><p className="mt-1 text-sm text-amber-800">Sign in with the account connected to your Student ID to see your assigned classes.</p><Link href={`/login?redirectedFrom=${encodeURIComponent("/live-classes")}`} className="mt-4 inline-flex rounded-xl bg-[#14256f] px-5 py-3 text-sm font-black text-white">Student Login</Link></div>}
  {!loading&&!error&&<div className="mt-6 grid gap-4 md:grid-cols-2">{(data?.classes||[]).map((c:any)=><article key={c.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2">{c.status==="live"?<span className="rounded-full bg-red-50 px-2 py-1 text-[11px] font-black text-red-600">● LIVE</span>:<span className="text-[11px] font-black uppercase text-slate-400">{c.status}</span>}</div><h2 className="mt-2 text-xl font-black">{c.title}</h2><p className="text-sm font-semibold text-slate-500">{c.topic}</p></div><div className="rounded-xl bg-[#14256f]/5 p-3 text-[#14256f]">{c.status==="completed"?<PlayCircle className="h-5 w-5"/>:<CalendarDays className="h-5 w-5"/>}</div></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-400">Faculty</span><div className="font-black">{c.faculty_name}</div></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-400">Time</span><div className="font-black">{new Date(c.starts_at).toLocaleString()}</div></div></div><div className="mt-4 flex items-center justify-between text-xs text-slate-400"><span className="inline-flex items-center gap-1"><FileText className="h-3.5 w-3.5"/>{c.resources?.length||0} resources</span><span className="inline-flex items-center gap-1"><Users className="h-3.5 w-3.5"/>Access granted</span></div><Link href={`/live-classes/${c.id}`} className={`mt-5 flex w-full items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-black text-white ${c.status==="live"?"bg-green-600":"bg-[#14256f]"}`}>{c.status==="completed"?<><PlayCircle className="h-4 w-4"/>Watch Replay</>:<><Radio className="h-4 w-4"/>Open Class</>}</Link></article>)}{!data?.classes?.length&&<div className="md:col-span-2 rounded-3xl border bg-white p-10 text-center"><h2 className="font-black">No live classes assigned yet</h2><p className="mt-2 text-sm text-slate-500">When you purchase a package or staff assigns a class, it will appear automatically.</p></div>}</div>}</div></main>;
}
