import { requireZoomConfig } from "@/lib/zoom/config";
type Meta={webinarId:string;password:string;hostEmail:string;joinUrl:string;createdAt:string};
function key(classId:string){return `zoom_class:${classId}`;}
export async function getZoomAccessToken(){const c=requireZoomConfig();const basic=Buffer.from(`${c.apiClientId}:${c.apiClientSecret}`).toString("base64");const r=await fetch(`https://zoom.us/oauth/token?grant_type=account_credentials&account_id=${encodeURIComponent(c.accountId)}`,{method:"POST",headers:{Authorization:`Basic ${basic}`,"Content-Type":"application/x-www-form-urlencoded"},cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.access_token)throw Object.assign(new Error(d?.reason||d?.error||d?.message||`Zoom OAuth failed with HTTP ${r.status}.`),{status:502});return String(d.access_token);}
async function api<T>(path:string,init:RequestInit={}){const token=await getZoomAccessToken();const r=await fetch(`https://api.zoom.us/v2${path}`,{...init,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(init.headers||{})},cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d?.message||d?.reason||`Zoom API failed with HTTP ${r.status}.`),{status:r.status>=500?502:r.status});return d as T;}
export async function getZoomZak(userId:string){const d=await api<{token?:string}>(`/users/${encodeURIComponent(userId)}/token?type=zak`);if(!d.token)throw Object.assign(new Error("Zoom did not return a host ZAK token."),{status:502});return String(d.token);}
export async function loadZoomClassMetadata(service:any,classId:string):Promise<Meta|null>{const {data}=await service.from("live_class_settings").select("value").eq("key",key(classId)).maybeSingle();if(!data?.value)return null;try{const x=JSON.parse(String(data.value));return x?.webinarId?x:null;}catch{return null;}}
async function save(service:any,classId:string,meta:Meta){const {error}=await service.from("live_class_settings").upsert({key:key(classId),value:JSON.stringify(meta),updated_at:new Date().toISOString()},{onConflict:"key"});if(error)throw error;}
export async function ensureZoomWebinar(service:any,liveClass:any):Promise<Meta>{const classId=String(liveClass.id||"");const existing=await loadZoomClassMetadata(service,classId);if(existing)return existing;const c=requireZoomConfig();const start=new Date(liveClass.starts_at||Date.now()).getTime();const end=liveClass.ends_at?new Date(liveClass.ends_at).getTime():start+3600000;const duration=Math.max(15,Math.min(1440,Math.ceil((end-start)/60000)));const created=await api<any>(`/users/${encodeURIComponent(c.hostEmail)}/webinars`,{method:"POST",body:JSON.stringify({topic:String(liveClass.title||liveClass.topic||"Ibemhal IAS Live Now"),type:5,start_time:new Date(start).toISOString(),duration,timezone:String(liveClass.timezone||"Asia/Kolkata"),agenda:String(liveClass.topic||""),settings:{approval_type:2}})});const webinarId=String(created?.id||"");if(!webinarId)throw Object.assign(new Error("Zoom did not return a webinar ID."),{status:502});const meta={webinarId,password:String(created?.password||""),hostEmail:c.hostEmail,joinUrl:String(created?.join_url||""),createdAt:new Date().toISOString()};await save(service,classId,meta);const {error}=await service.from("live_classes").update({provider:"zoom",provider_room_id:webinarId,join_url:meta.joinUrl||null,updated_at:new Date().toISOString()}).eq("id",classId);if(error)throw error;return meta;}
